server:
  port: 8093

spring:
  application:
    name: tracking-service
  datasource:
    url: jdbc:h2:mem:trackingdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
