spring:
  application:
    name: signalr-service
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8082

websocket:
  allowed-origins: "*"

logging:
  level:
    com.ecommerce: DEBUG
